/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/ligth_test.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ligth_test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0.049, 8.372, 0]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1, -8.357, -1]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.003']} scale={32.492} />
    </group>
  )
}

useGLTF.preload('/ligth_test.glb')
